### ISSUE TITLE
ConfiguracionManager class not found

### ISSUE THREAD

**Issue by olikster** [qmetry/qaf-cucumber#15]
Hi

I'm trying to use your plugin to run some tests in my Cucumber project. For that I've added your plugin to my Cucumber.class runner.

I've added externally your jar qaf-cucumber-2.1.15-beta-2, obtained from maven but when I try to run my test is failing due to error:
java.lang.NoClassDefFoundError: com/qmetry/qaf/automation/core/ConfigurationManager

I've checked .jar file and its correct, that class is not included but added as import in QAFCucumberPlugin.class

What I am doing wrong? 

Thanks!

**Comment by cjayswal** [comment]
`ConfigurationManager` is from qaf. Will you make sure that `qaf` dependency resolved? If you just placed jar `qaf-cucumber` in classpath it may not work. You need to add as dependency  for example, if using maven add it in your POM.

**Comment by olikster** [comment]
Thats the issue. I've added qaf-cucumber and qaf-support also and it works.
