### ISSUE TITLE
Cucumber step with Data table having more than one argument is not working when we run with TestNG using BDDFactory2

### ISSUE THREAD

**Issue by Theneskumar** [qmetry/qaf-cucumber#3]
QAF version:
3.0.0-beta-1

Example when we have step definition
```
@When("Sample {string} and Data Table")
public void step1(String str, DataTable dataTable){
System.out.println("DataTable");
}
```
and BDD

```
When Sample "value" and Data Table
|user|
|Test|
|Test2|
```
Then is it working when we run as cucumber test , However when run as testng using QAF it is throwing step not found. When we modify step with one more param it is working on QAF however Cucumber throw error

Workarround: adding placeholder for datatable argument resolves the problem.

```
@When("Sample {string} and Data Table{table}")
```

**Comment by cjayswal** [comment]
Closed in https://github.com/qmetry/qaf-cucumber/commit/dcbec14dde076ec07ffbc751168320c22d5d23cc
